services:
  qgis:
    image: qgis/qgis:${QGIS_VERSION}
    container_name: qgis
    volumes:
      - ../:/tests_directory
    environment:
      # - DISPLAY=unix$DISPLAY
      - CI=True
      - DISPLAY=:99